### ISSUE TITLE
Players with realms such as "Burning-Legion" don't have the correct check-pvp link.

### ISSUE THREAD

**Issue by NotAgentBilly** [wowarenalogs/wowarenalogs#217]
For example, the character "Kriszi-BurningLegion", the link from wow arena logs is "https://check-pvp.fr/eu/Burning-Legion/Kriszi" whereas the real link is "https://check-pvp.fr/eu/Burning%20Legion/Kriszi".

Perhaps this is a bug on check-pvp side, but I don't know.

-- another example that doesn't work: https://check-pvp.fr/eu/Aggra%5BPortugu%C3%AAs%5D/Nahir (Aggra[Português]/Nahir), should be https://check-pvp.fr/eu/Aggra%20%28Portugu%C3%AAs%29/Nahir (Aggra (Português)/Nahir)

**Comment by prsauer** [comment]
This should be resolved, I have not been able to reproduce a case with incorrect linking

If noticed again - please link to the match, thanks!
