### ISSUE TITLE
Video recording sometimes blank

### ISSUE THREAD

**Issue by OperationXen** [wowarenalogs/wowarenalogs#315]
A few times I've come to watch videos and found them to be just a black screen, I think this may be caused by starting WoWArenaLogs whilst the WoW client is already running

**Comment by OperationXen** [comment]
My config seems to be OK when this happens, it's configured for game capture with cursor

**Comment by OperationXen** [comment]
Also when this occurs the audio is recorded as expected

**Comment by prsauer** [comment]
@OperationXen We've had a few people report this and traced it back to disk being full -- possible that was happening?

**Comment by prsauer** [comment]
Please re-open after 4.8.0 if this is still happening.
